### ISSUE TITLE
Logo license concern

### ISSUE THREAD

**Issue by chunlaw** [LOOHP/HK-Bus-ETA-WearOS#1]
Hi James, I have seen your app in Play Store and seems the bus in your logo is derived from KMB bus app. It looks like the usage is beyond the notion of [fair use](https://fairuse.stanford.edu/overview/fair-use/what-is-fair-use/), and it may get into trouble of copyright infringement. It may be safer to draw a new logo.

**Comment by LOOHP** [comment]
Thanks for the reminder. Although I actually didn't use any copy and paste, I'll change it up a bit. Thank you.
