### ISSUE TITLE
[Off-topic] Icon WearOS

### ISSUE THREAD

**Issue by cagnulein** [LOOHP/HK-Bus-ETA-WearOS#2]
Thanks for the tip of the rounded icon!
It worked for the review on Google Play store last month, but today the rejected it again today after 5 approved version! It's incredible!
Is your still working ok on the review?

**Comment by LOOHP** [comment]
It's currently still up, tho I'm currently waiting for my app update to be approved. Will update you with the results once it is approved/rejected.

**Comment by cagnulein** [comment]
thanks! i'm so mad with google! if only they will explain clearly the issue
or at least with a video of the issue!

**Comment by cagnulein** [comment]
unbelieavable: yesterday i put the wear os setting in the developer portal to off in order to be able anyway to push my android app without the wear os. Then after 1 hour i tried to put it to "on" again (i was sure they would reject my app again of course since i didn't upload any new binary yet).
Today google reviews my app with wear os just fine!
They are so crazy! It's impossible to work in this way!

**Comment by LOOHP** [comment]
Glad that it eventually worked for you. I also initially got rejected for content overflowing out of screen, they even included a screenshot... of nothing overflowing out of screen. I resubmitted the same app and then it got approved.

**Comment by cagnulein** [comment]
again ![image](https://github.com/LOOHP/HK-Bus-ETA-WearOS-WatchOS/assets/48216/d579795f-4e94-4181-85cc-5a10582ea566)

**Comment by cagnulein** [comment]
as before, removed wearos support and enable it back fixed the issue.
stupid google
